<a href="https://colab.research.google.com/github/Harivamsh2005/Python-For-data-Science/blob/main/Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Mathematical Operations on 2D Arrays

In [1]:
import numpy as np

A = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

B = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("\nArray A:")
print(A)

print("\nArray B:")
print(B)

# Addition
print("\nAddition (A + B):")
print(A + B)

# Subtraction
print("\nSubtraction (A - B):")
print(A - B)

# Element-wise Multiplication
print("\nElement-wise Multiplication (A * B):")
print(A * B)

# Element-wise Division
print("\nElement-wise Division (A / B):")
print(A / B)

# Matrix Multiplication
C = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

print("\nMatrix C:")
print(C)

print("\nMatrix Multiplication (A @ C):")
print(A @ C)


Array A:
[[10 20 30]
 [40 50 60]]

Array B:
[[1 2 3]
 [4 5 6]]

Addition (A + B):
[[11 22 33]
 [44 55 66]]

Subtraction (A - B):
[[ 9 18 27]
 [36 45 54]]

Element-wise Multiplication (A * B):
[[ 10  40  90]
 [160 250 360]]

Element-wise Division (A / B):
[[10. 10. 10.]
 [10. 10. 10.]]

Matrix C:
[[1 2]
 [3 4]
 [5 6]]

Matrix Multiplication (A @ C):
[[220 280]
 [490 640]]


Creating and Checking a 3D NumPy Array

In [3]:
import numpy as np

A = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(A)

print("Shape:", A.shape)
print("Dimensions:", A.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Dimensions: 3
