<a href="https://colab.research.google.com/github/Harivamsh2005/Python-For-data-Science/blob/main/Lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creating a One-Dimensional NumPy Array

In [1]:
import numpy as np

marks = np.array([85, 90, 78, 88, 92])

print(marks)

[85 90 78 88 92]


Creating a Two-Dimensional NumPy Array

In [2]:
import numpy as np

student_marks = np.array([
    [85, 90, 78],
    [88, 76, 91],
    [92, 84, 80]
])

print(student_marks)

[[85 90 78]
 [88 76 91]
 [92 84 80]]


Basic NumPy Array Operations

In [3]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Display the array
print("Array :", arr)

# Basic operations
print("Maximum Value :", arr.max())
print("Minimum Value :", arr.min())
print("Sum :", arr.sum())
print("Average :", arr.mean())
print("Number of Elements :", arr.size)

Array : [10 20 30 40 50]
Maximum Value : 50
Minimum Value : 10
Sum : 150
Average : 30.0
Number of Elements : 5


Array Indexing, Slicing, Arithmetic & Reshaping

In [4]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])  # Create an array

# Indexing
print("First Element :", arr[0])
print("Last Element :", arr[-1])

# Slicing
print("Elements from Index 1 to 3 :", arr[1:4])

# Arithmetic operations
print("Array + 10 :", arr + 10)
print("Array × 2 :", arr * 2)

# Reshape
new_arr = arr.reshape(5, 1)

print("Reshaped Array:")
print(new_arr)

First Element : 10
Last Element : 50
Elements from Index 1 to 3 : [20 30 40]
Array + 10 : [20 30 40 50 60]
Array × 2 : [ 20  40  60  80 100]
Reshaped Array:
[[10]
 [20]
 [30]
 [40]
 [50]]


Creating a pandas DataFrame

In [5]:
import pandas as pd

data = {
    "Roll No": [101, 102, 103, 104],
    "Name": ["Ravi", "Priya", "Arun", "Meena"],
    "Marks": [85, 92, 78, 88]
}

df = pd.DataFrame(data)

print(df)

   Roll No   Name  Marks
0      101   Ravi     85
1      102  Priya     92
2      103   Arun     78
3      104  Meena     88


DataFrame Operations

In [6]:
import pandas as pd

# Create a DataFrame
data = {
    "Roll No": [101, 102, 103, 104],
    "Name": ["Ravi", "Priya", "Arun", "Meena"],
    "Marks": [85, 92, 78, 88]
}

df = pd.DataFrame(data)

# Display the DataFrame
print("DataFrame")
print(df)

# Display first two rows
print("\nFirst Two Rows")
print(df.head(2))

# Display last two rows
print("\nLast Two Rows")
print(df.tail(2))

# Display column names
print("\nColumn Names")
print(df.columns)

# Display DataFrame shape
print("\nShape")
print(df.shape)

# Display summary information
print("\nInformation")
print(df.info())

# Display statistical summary
print("\nStatistical Summary")
print(df.describe())

DataFrame
   Roll No   Name  Marks
0      101   Ravi     85
1      102  Priya     92
2      103   Arun     78
3      104  Meena     88

First Two Rows
   Roll No   Name  Marks
0      101   Ravi     85
1      102  Priya     92

Last Two Rows
   Roll No   Name  Marks
2      103   Arun     78
3      104  Meena     88

Column Names
Index(['Roll No', 'Name', 'Marks'], dtype='object')

Shape
(4, 3)

Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Roll No  4 non-null      int64 
 1   Name     4 non-null      object
 2   Marks    4 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes
None

Statistical Summary
          Roll No      Marks
count    4.000000   4.000000
mean   102.500000  85.750000
std      1.290994   5.909033
min    101.000000  78.000000
25%    101.750000  83.250000
50%    102.500000  86.500000
75%    103.250000  89.